/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    aws_project_region: 'us-east-1',
    // aws_cognito_identity_pool_id: 'us-east-2:f601ad7b-b9fc-4e4a-9163-9d12d393fd7f',
    // aws_cognito_identity_pool_id: '',

    aws_cognito_region: 'us-east-1',
    // aws_user_pools_id: 'us-east-2_zG2SfHpXC',
    aws_user_pools_id: 'us-east-1_BO2rSGqTd',

    aws_user_pools_web_client_id: 'duquj0kkirg431tdu9ketn7vp',
    oauth: {},
    aws_cognito_login_mechanism: [],
    aws_cognito_signup_attributes: ['EMAIL'],
    aws_cognito_mfa_configuration: 'OFF',
    aws_cognito_mfa_types: ['SMS'],
    aws_cognito_password_protection_settings: {
        passwordPolicyMinLength: 8,
        passwordPolicyCharacters: [],
    },
};

export default awsmobile;